[project]
name = "hardware-store-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.125.0",
    "httpx>=0.28.1",
    "passlib>=1.7.4",
    "pydantic[email]>=1.10.9",
    "pymysql>=1.1.2",
    "python-dotenv>=1.2.2",
    "rasa>=3.6.21",
    "sqlalchemy>=1.4.54",
    "uvicorn>=0.41.0",
]
